#!/opt/puppetlabs/puppet/bin/ruby

$LOAD_PATH.unshift(File.expand_path(File.join(__dir__, 'lib')))

required_directories = [
  '/etc/puppetlabs/puppet',
  '/etc/puppetlabs/code/environments',
  '/var/run/puppet'
]

require 'fileutils'
FileUtils.mkdir_p(required_directories)
FileUtils.chown_R('puppet', 'puppet', required_directories)

# For some reason, the CA directory and items are not getting chown'd properly
# Since we're running this in single-point containers, there really isn't
# anything to get broken into.
#
# We should try to fix this in the future, but it may become largely irrelevant
# if all goes to plan.
args = ['--no-daemonize', '--user=root', '--group=root', '--masterport=8140']

require 'puppet/util/command_line'
Puppet::Util::CommandLine.new('master', args).execute
