#!/opt/puppetlabs/puppet/bin/ruby

$LOAD_PATH.unshift(File.expand_path(File.join(__dir__, 'lib')))

required_directories = [
  '/etc/puppetlabs/puppet',
  '/etc/puppetlabs/code/environments',
  '/var/run/puppet'
]

require 'fileutils'
FileUtils.mkdir_p(required_directories)
FileUtils.chown_R('puppet', 'puppet', required_directories)

args = [ ]

require 'puppet/util/command_line'
Puppet::Util::CommandLine.new('master', args).execute
