#!/bin/sh

mkdir -p rundir/puppet
mkdir -p rundir/server/data/puppetmaster
mkdir -p rundir/log/puppetlabs/puppetmaster
mkdir -p rundir/run/puppetlabs/puppetmaster
mkdir -p rundir/etc/puppetlabs/code

bundle exec puppet master \
  --no-daemonize \
  --confdir $PWD/rundir/puppet \
  --vardir $PWD/rundir/server/data/puppetmaster \
  --logdir $PWD/rundir/log/puppetlabs/puppetmaster \
  --rundir $PWD/rundir/run/puppetlabs/puppetmaster \
  --codedir $PWD/rundir/etc/puppetlabs/code \
  --trace
